import React from 'react';
import { ComponentMeta } from '@storybook/react';
declare const _default: ComponentMeta<({ variant, color, className, renderAs, style, label, }: {
    variant?: "h1" | "h2" | "h3" | "h4" | "h2_light" | "h3_light" | "base_big_bold" | "base_big_sb" | "base_big_m" | "body_big_b" | "body_big_sb" | "body_big_m" | "body_m" | "body_b" | "body_sb" | "body_ul" | "body_st" | "body_para_m" | "body_para_sb" | "body_para_b" | "body_para_ul" | "body_para_st" | "small_m" | "small_sb" | "small_b" | "small_ul" | "small_st" | "small_uppercase" | "small_para_m" | "small_para_sb" | "small_para_b" | "small_para_ul" | "small_para_st" | "tiny_m" | "tiny_sb" | "tiny_b" | "tiny_ul" | "tiny_st" | "tiny_uppercase";
    color?: "transparent" | "interaction_10" | "interaction_20" | "interaction_30" | "interaction_40" | "interaction_50" | "interaction_60" | "interaction_buttons" | "interaction_80" | "interaction_90" | "interaction_100" | "positive_10" | "positive_20" | "positive_30" | "positive_40" | "positive_50" | "positive_60" | "positive_text" | "positive_80" | "positive_90" | "positive_100" | "negative_10" | "negative_20" | "negative_30" | "negative_40" | "negative_50" | "negative_60" | "negative_text" | "negative_80" | "negative_90" | "negative_100" | "warning_10" | "warning_20" | "warning_30" | "warning_40" | "warning_50" | "warning_text" | "warning_70" | "warning_80" | "warning_90" | "warning_100" | "grey_background" | "grey_stroke-divider" | "text_placeholder" | "text_label" | "text_subheading" | "text_caption" | "text_default" | "grey_white" | "grey_10" | "grey_20" | "grey_30" | "grey_40" | "grey_50" | "grey_60" | "grey_70" | "grey_80" | "grey_90" | "grey_black" | "emerald_10" | "emerald_20" | "emerald_30" | "emerald_40" | "emerald_50" | "emerald_60" | "emerald_70" | "emerald_80" | "emerald_90" | "emerald_100" | "rosewood_10" | "rosewood_20" | "rosewood_30" | "rosewood_40" | "rosewood_50" | "rosewood_60" | "rosewood_70" | "rosewood_80" | "rosewood_90" | "rosewood_100" | "blue_10" | "blue_20" | "blue_30" | "blue_40" | "blue_50" | "blue_60" | "blue_70" | "blue_80" | "blue_90" | "blue_100" | "orange_10" | "orange_20" | "orange_30" | "orange_40" | "orange_50" | "orange_60" | "orange_70" | "orange_80" | "orange_90" | "orange_100";
    renderAs?: "P" | "H1" | "H2" | "H3" | "H4" | "H5" | "H6" | "SPAN" | "Div";
    className?: string;
    style?: React.CSSProperties;
    label: any;
}) => any>;
export default _default;
export declare const Default: any;
